-- 001_create_test_tables.sql
-- Idempotent migration to create test tables and an audit log for recalculation
-- Intended to run against the same Supabase project as production but used only
-- for safe, admin-driven recalibration testing.

-- Create test_sessions (mirrors sessions)
CREATE TABLE IF NOT EXISTS public.test_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  player_id BIGINT NOT NULL,
  session_date timestamptz NOT NULL,
  notes text,
  is_test boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Create test_session_stats (mirrors session_stats)
CREATE TABLE IF NOT EXISTS public.test_session_stats (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id BIGINT NOT NULL,
  player_id BIGINT NOT NULL,
  skill_type text,
  c numeric,
  p numeric,
  a numeric,
  s numeric,
  t numeric,
  normalized_value numeric,
  normalized_band text,
  is_test boolean NOT NULL DEFAULT true,
  version integer NOT NULL DEFAULT 1,
  recalibrated_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT fk_test_session FOREIGN KEY (session_id) REFERENCES public.test_sessions(id) ON DELETE CASCADE
);

-- Create stat_recalculation_log to record recalculation runs and manual overrides
CREATE TABLE IF NOT EXISTS public.stat_recalculation_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  player_id BIGINT NOT NULL,
  mode text NOT NULL, -- 'test' or 'production'
  triggered_by text, -- admin identifier (email or uid)
  notes text,
  run_at timestamptz NOT NULL DEFAULT now(),
  details jsonb -- store before/after and other structured data
);

-- Ensure extensions commonly used
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Row Level Security: enable RLS on test tables and provide example policies
-- These policies restrict read/write to JWTs that include claim role = 'admin'.
-- Supabase service_role bypasses RLS and will continue to have full access.

-- Enable RLS
ALTER TABLE IF EXISTS public.test_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.test_session_stats ENABLE ROW LEVEL SECURITY;

-- Policy: allow admins (jwt.claims.role = 'admin') to SELECT/INSERT/UPDATE/DELETE
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_catalog.pg_roles WHERE rolname = 'anon_admin_policy_marker'
  ) THEN
    -- marker role is not used; this block is a no-op but keeps migration idempotent
    NULL;
  END IF;
END$$;

-- helper expression: jwt role claim equals 'admin'
-- current_setting('jwt.claims.role', true) will return NULL when not set

-- test_sessions policies
CREATE POLICY IF NOT EXISTS test_sessions_admin_policy ON public.test_sessions
  FOR ALL USING (
    (current_setting('jwt.claims.role', true) = 'admin')
  ) WITH CHECK (
    (current_setting('jwt.claims.role', true) = 'admin')
  );

-- test_session_stats policies
CREATE POLICY IF NOT EXISTS test_session_stats_admin_policy ON public.test_session_stats
  FOR ALL USING (
    (current_setting('jwt.claims.role', true) = 'admin')
  ) WITH CHECK (
    (current_setting('jwt.claims.role', true) = 'admin')
  );

-- Allow admins to view the log
ALTER TABLE IF EXISTS public.stat_recalculation_log ENABLE ROW LEVEL SECURITY;
CREATE POLICY IF NOT EXISTS recalculation_log_admin_policy ON public.stat_recalculation_log
  FOR SELECT USING (
    (current_setting('jwt.claims.role', true) = 'admin')
  );

-- Add helpful indexes
CREATE INDEX IF NOT EXISTS idx_test_sessions_player_id ON public.test_sessions (player_id);
CREATE INDEX IF NOT EXISTS idx_test_stats_player_id ON public.test_session_stats (player_id);
CREATE INDEX IF NOT EXISTS idx_stat_recalc_player_id ON public.stat_recalculation_log (player_id);

-- Notes for operators:
-- 1) Run this migration in your Supabase SQL editor or via psql connected to the project.
-- 2) The RLS examples use the JWT claim 'role' == 'admin'. Ensure your auth JWTs include this claim for admin users.
-- 3) The service_role key bypasses RLS; server-side code should use the service role when performing upserts from API routes.
