// Extended Band schema to match diagnostic flow: process -> breakdown -> outcomes -> refuses -> anchors
// Backwards-compatible: `description` remains optional while entries are migrated.
export type Band = {
  min: number;
  max: number;
  name: string;

  // What the process looks like (observable checklist)
  process?: string[];
  // When it breaks down (stress/fatigue/complexity)
  breakdown?: string[];
  // Result patterns and outcomes
  outcomes?: string[];
  // Common failure traits that are absent at this band
  refuses?: string[];
  // Concrete anchors / examples
  anchors?: string[];

    // Legacy single-paragraph description (temporary, for compatibility)
    description?: string;
  };
  
  export const serve: Record<string, Band[]> = {
    consistency: [
      {
        min: 0,
        max: 6,
        name: "Unstable",
          description: "Serve mechanics lack repeatability and structural control. Toss, contact point, and balance vary widely, leading to frequent double faults or soft, attackable serves. Quality is accidental rather than constructed.",
        process: [
          "Toss location and contact point vary visibly between attempts",
          "Preparation routine is inconsistent or absent",
        ],
        breakdown: ["Routine fails on most attempts; cannot sustain across reps"],
        refuses: ["Cannot produce a repeatable preparation or start points reliably"],
        outcomes: ["Frequent missed serves, sitters, or defensive first balls"],
        anchors: [
          "Toss lands in different places serve-to-serve",
          "Contact point shifts on most attempts",
        ],
      },
      {
        min: 7,
        max: 12,
        name: "Conditional",
          description: "Serve is reliable inside a comfort zone, with moderate pace and basic spin control. Breakdowns occur when asked to increase pace, vary direction, or respond to return pressure. Execution depends on stable external conditions.",
        process: [
          "Routine and toss look repeatable during calm, fed, or low-pressure reps",
          "Rhythm establishes in cooperative practice",
        ],
        breakdown: ["Loses structure when pace, scoring pressure, or moderate fatigue increases"],
        refuses: ["Cannot preserve repeatability under standard match pressure"],
        outcomes: ["Performs in warm‑ups but degrades in live point play"],
        anchors: [
          "Routine repeats in basket feeding",
          "Rhythm collapses in live points",
        ],
      },
      {
        min: 13,
        max: 18,
        name: "Functional",
          description: "Serve mechanics are repeatable with consistent toss, contact, and balance. Player can stack multiple quality first serves and construct points intentionally. Breakdowns occur only under sustained or tactical pressure.",
        process: [
          "Toss and contact are predictable in practice and many routine match moments",
          "Preparation routine is consistent most of the time",
        ],
        breakdown: ["Visible mechanical or timing lapses during important points or long service games"],
        refuses: ["Cannot sustain flawless structure through extended pressure sequences"],
        outcomes: ["Usually starts points successfully; occasional lapses under high pressure"],
        anchors: [
          "Coach can predict serve shape most attempts",
          "Starts points reliably in routine play",
        ],
      },
      {
        min: 19,
        max: 24,
        name: "Competitive",
          description: "Serve is tactically integrated and stable under match pressure. Pace, spin, and directional variation are reliable, with low error rates. Mistakes appear only under elevated return intensity or fatigue.",
        process: [
          "Toss, contact and rhythm are preserved during typical match-pressure situations",
          "Routine remains intact while constructing points tactically",
        ],
        breakdown: ["Breaks under strong, well-executed pressure."],
        refuses: ["Not prone to frequent double faults or obvious mis-contacts in match play"],
        outcomes: ["Dependable serve outcomes with low service error rates in matches"],
        anchors: [
          "Serve quality is maintained during pressure points",
          "Toss and contact look consistent across games",
        ],
      },
      {
        min: 25,
        max: 30,
        name: "Advanced / Pro-Track",
          description: "Serve has a clear identity across flat, slice, and kick variations with intentional placement and disguise. Pressure is layered through serve +1 patterns. Breakdowns are brief and self-correcting.",
        process: [
          "Maintains toss, contact and rhythm deep into matches and long sessions",
          "Can deliberately vary serve type while preserving core mechanics",
        ],
        breakdown: ["Breaks under sustained or layered pressure."],
        refuses: ["Does not lose structural integrity when changing serve type or under normal fatigue"],
        outcomes: ["Can scale power and placement deliberately without mechanical loss"],
        anchors: [
          "Preserves serve structure deep into sessions",
          "Varies serve type without visible mechanical change",
        ],
      },
      {
        min: 31,
        max: 40,
        name: "Tour Challenger",
          description: "Serve is a consistent weapon with near-max pace, precision depth, and effective disguise. High-quality sequences can be sustained with minimal variance. Breakdown is rare and short-lived.",
        process: [
          "Preparation and contact are effectively identical across serve types",
          "Uses subtle variations to disguise intent while mechanics remain automated",
        ],
        breakdown: ["Breaks only under exceptional execution."],
        refuses: ["Opponents cannot reliably anticipate serve type from preparation"],
        outcomes: ["Automatic execution with elite disguise and intent"],
        anchors: [
          "Different serves originate from the same preparation",
          "Serve quality unchanged regardless of score or fatigue",
        ],
      },
      {
        min: 41,
        max: 50,
        name: "Tour Elite",
        description: "Serve operates at elite maximum pace with suffocating precision, disguise, and repeatability. Directional execution and depth control remain stable under extreme pressure. Momentum rarely shifts off serve.",
        process: [
          "Preparation and contact are effectively identical across serve types",
          "Uses subtle variations to disguise intent while mechanics remain automated",
        ],
        breakdown: ["Breaks only under exceptional execution."],
        refuses: ["Opponents cannot reliably anticipate serve type from preparation"],
        outcomes: ["Automatic execution with elite disguise and intent"],
        anchors: [
          "Different serves originate from the same preparation",
          "Serve quality unchanged regardless of score or fatigue",
        ],
      },
    ],
    overall: [
      {
        min: 0,
        max: 6,
        name: "Unstable",
        description: "Serve mechanics lack repeatability and structural control. Toss, contact point, and balance vary widely, leading to frequent double faults or soft, attackable serves. Quality is accidental rather than constructed.",
        process: [
          "Serve routine is inconsistent or incomplete",
          "Grip may shift unintentionally between attempts",
          "Toss varies widely in height and location",
          "Contact point is often too low or too far forward/back",
          "Limited use of legs or trunk rotation",
          "Motion may resemble a push or guided hit rather than a full service action",
          "Can occasionally land a clean serve, but not predictably",
          "Quality is accidental more than constructed",
        ],
        breakdown: [
          "Any attempt to aim to a specific side",
          "Any increase in pace",
          "Second serve situations",
          "Score awareness",
          "Minor distraction or hesitation",
          "Breakdown threshold is very low.",
        ],
        outcomes: [
          "Frequent missed first serves",
          "Multiple double faults per game",
          "Second serves that are soft and attackable",
          "Short serves that bounce inside the service box",
          "Immediate loss of control in the rally",
          "Points often start defensively or end before a rally develops.",
        ],
        refuses: ["None"],
        anchors: [
          "Game at 2–2. Player:\nMisses first serve into the net\nMisses second serve long",
          "First serve goes in softly down the middle\nOpponent returns aggressively",
          "First serve clips in and opponent misses return\nPoint won through opponent error or a single clean contact, not through repeatable serving structure or intentional targeting.",
        ],
      },
      {
        min: 7,
        max: 12,
        name: "Conditional",
        description: "Serve is reliable inside a comfort zone, with moderate pace and basic spin control. Breakdowns occur when asked to increase pace, vary direction, or respond to return pressure. Execution depends on stable external conditions.",
        process: [
          "Serve routine is fairly consistent, with preparation and toss mostly reliable",
          "First serve occasionally lands with pace or spin, second serve generally safe",
          "Contact height and toss location are generally within a comfortable range",
          "Can hit short sequences of solid serves (2–3 in a row)",
          "Quality depends on comfort zone and rally context",
          "Process holds if conditions are comfortable.",
        ],
        breakdown: [
          "Opponent adjusts return position or steps in aggressively",
          "Forced wide or body-targeted serves",
          "Directional placement outside comfort zone",
          "Slight fatigue or distraction",
          "Player attempts first-serve pace/spin combination beyond reliable execution",
          "Breakdown tied to external condition shifts.",
        ],
        outcomes: [
          "First serve error (wide or into net)",
          "Second serve rushed or slightly short",
          "Over-rotated or off-balance serve",
          "Short or attackable serve that allows opponent easy put-away",
          "Point often shifts from offensive to neutral or defensive.",
        ],
        refuses: [
          "Total inability to serve",
          "Chronic double faults",
          "Complete mechanical disorganization",
        ],
        anchors: [
          "Game at 1–1. Player:\nServes 2–3 safe first serves in a row\nOpponent steps in on third point",
          "First serve occasionally lands with pace or spin; second serve generally safe",
          "When they win points from offense, it’s usually: because opponent cracks first or because the serve was within comfort zone and executed with solid pace or spin",
        ],
      },
      {
        min: 13,
        max: 18,
        name: "Functional",
        description: "Serve mechanics are repeatable with consistent toss, contact, and balance. Player can stack multiple quality first serves and construct points intentionally. Breakdowns occur only under sustained or tactical pressure.",
        process: [
          "Serve routine is consistent and reliable under pressure",
          "Toss location and contact point are repeatable",
          "Can hit 3–5 first serves in a row with moderate pace and spin",
          "Second serve is safe, with controlled depth and moderate spin",
          "Can construct points off serve, targeting preferred zones",
          "Quality is repeatable and allows defensive or offensive follow-up",
        ],
        breakdown: [
          "Opponent anticipates or adjusts to serve pattern",
          "Sustained high-speed rallies after serve",
          "Wide or body serves under pressure",
          "Fatigue late in sets",
          "Slight misjudgment of toss or timing",
          "Breakdown now requires actual pressure.",
        ],
        outcomes: [
          "First serve misses wide or into net",
          "Second serve becomes slightly short or attackable",
          "Ball depth reduces, giving opponent easier returns",
          "Points can shift from offensive to neutral if first serve fails",
        ],
        refuses: [
          "Chronic double faults",
          "Total inability to target or execute serve",
          "Complete mechanical disorganization",
        ],
        anchors: [
          "Game at 2–2. Player:\nServes three solid first serves to preferred targets\nOpponent steps in on third serve",
          "Player executes second serve safely with spin\nPlayer steps in and finishes with planned placement",
        ],
      },
      {
        min: 19,
        max: 24,
        name: "Competitive",
        description: "Serve is tactically integrated and stable under match pressure. Pace, spin, and directional variation are reliable, with low error rates. Mistakes appear only under elevated return intensity or fatigue.",
        process: [
          "Serve routine is highly consistent under match pressure",
          "Contact point, toss, and racquet path are repeatable",
          "Can hit 4–6 first serves in a row with pace, spin, or slight variation",
          "Second serve is reliable, with controlled depth and moderate to heavy spin",
          "Can construct points off serve tactically",
          "Quality is mostly stable, with minor variation in speed or placement",
          "Can disguise serve direction effectively",
        ],
        breakdown: [
          "Breaks under strong, well-executed opponent pressure",
          "Elevated intensity or sustained returns",
          "Sudden pace increase or well-placed returns",
          "Opponent adjustments create a scenario where your intended serve direction must change quickly",
          "Fatigue in longer matches or rallies",
          "Minor timing or depth fluctuations",
        ],
        outcomes: [
          "Low error rates, with occasional serve landing shorter or slightly attackable",
          "Serve percentage may dip briefly under pressure",
          "Rally control may shift temporarily",
          "Breakdowns can persist for multiple points",
        ],
        refuses: [
          "Frequent double faults",
          "Wild mis-hits",
          "Inability to serve reliably",
        ],
        anchors: [
          "Game at 2–2. Player:\nHits four solid first serves in a row with pace and placement\nOpponent adjusts on fifth serve",
          "Player executes second serve safely with spin\nOpponent returns short\nPlayer steps in and finishes the point",
        ],
      },
      {
        min: 25,
        max: 30,
        name: "Advanced / Pro-Track",
        description: "Serve has a clear identity across flat, slice, and kick variations with intentional placement and disguise. Pressure is layered through serve +1 patterns. Breakdowns are brief and self-correcting.",
        process: [
          "First serve speed and spin are repeatable under pressure",
          "Clear identity between flat, slice, and kick serves",
          "Can locate wide, body, and T on both sides with intention",
          "Toss location is stable and supports disguise",
          "Maintains balance and extension through contact",
          "Second serve has shape, height, and margin — not just safety",
          "Can stack 3–5 high-quality service points in a row",
          "Serve patterns are intentional (serve +1 is planned)",
        ],
        breakdown: [
          "Breaks under sustained scoreboard or return pressure",
          "Long deuce games with repeated second serves",
          "Opponent aggressively attacking second serve",
          "Fatigue affecting leg drive and toss consistency",
          "Deliberate max-power serving sequences",
          "Breakdowns are brief and self-corrected.",
        ],
        outcomes: [
          "Slight reduction in first serve percentage",
          "Occasional second serve landing shorter in the box",
          "One over-press first serve miss",
          "Minor toss drift leading to slight contact inconsistency",
          "But recalibration occurs quickly; momentum rarely collapses.",
        ],
        refuses: [
          "Double faults in clusters under routine pressure",
          "Second serve that sits attackable without shape",
          "Predictable serve direction patterns",
        ],
        anchors: [
          "Game at 4–4. Advanced player:\nHits wide slice in deuce court and forces return 3–4 feet behind baseline then finishes within two balls",
          "Kicks second serve above shoulder height and neutralizes aggressive returner",
        ],
      },
      {
        min: 31,
        max: 40,
        name: "Tour Challenger",
        description: "Serve is a consistent weapon with near-max pace, precision depth, and effective disguise. High-quality sequences can be sustained with minimal variance. Breakdown is rare and short-lived.",
        process: [
          "First serve speed and spin are repeatable at near-max pace",
          "Can disguise flat, slice, and kick serves effectively",
          "Depth consistently lands within 1–3 feet of the service box line",
          "Directional choices are executed late to mask intention",
          "Can stack 8–12 high-quality serves in a row",
          "Balance and leg drive preserved through full extension",
          "Minimal shot-to-shot variance",
          "Process is suffocating and repeatable.",
        ],
        breakdown: [
          "Breaks only under exceptional circumstances.",
          "Extreme physical fatigue (late 3rd set, high-volume serving)",
          "Opponent consistently anticipates spin or location perfectly",
          "Rare timing or contact point slips",
        ],
        outcomes: [
          "Slightly slower or shorter first serve",
          "Rare over-hit second serves; immediate recovery for follow-up shot",
          "Serve remains a consistent weapon throughout; momentum almost never swings from a single lapse",
        ],
        refuses: [
          "Repeated double faults under normal conditions",
          "Loss of serve depth under neutral conditions",
          "Mechanical sequencing errors",
        ],
        anchors: [
          "Service game at 4–4. Tour Challenger player:\nHits 6 high-speed first serves\nOpponent reads spin but misjudges placement\nPlayer disguises direction until last millisecond\nBall lands within inches of sideline\nOpponent stretches, floating defensive return\nPlayer steps in for put-away winner",
        ],
      },
      {
        min: 41,
        max: 50,
        name: "Tour Elite",
        description: "Serve operates at elite maximum pace with suffocating precision, disguise, and repeatability. Directional execution and depth control remain stable under extreme pressure. Momentum rarely shifts off serve.",
        process: [
          "First serve speed and spin are at elite max pace",
          "Can consistently disguise flat, slice, and kick serves",
          "Depth lands within 1–3 feet of the service box line with near-perfect placement",
          "Directional changes executed at the last millisecond to mask intent",
          "Can stack 8–12 high-quality serves in a row",
          "Leg drive, toss, and balance maintained through full extension",
          "Minimal shot-to-shot variance, process is suffocating and repeatable",
          "Serve pressure is dominant and persistent, forcing defensive returns.",
        ],
        breakdown: [
          "Breaks only under exceptional conditions.",
          "Extreme physical fatigue (late 3rd set, multiple long games)",
          "Opponent anticipates spin or placement with perfect precision",
          "Rare timing slip under extreme stretch",
        ],
        outcomes: [
          "Slightly shorter first serve",
          "Rare over-hit second serve",
          "Immediate recovery for follow-up shot",
          "Momentum almost never swings from a single lapse",
        ],
        refuses: [
          "Double faults under normal conditions",
          "Loss of depth or placement under neutral pressure",
          "Mechanical sequencing errors",
        ],
        anchors: [
          "Service game at 5–5. Tour Elite player:\nHits 6 first serves at maximum pace\nOpponent reads spin but misjudges placement\nPlayer disguises direction until last millisecond\nBall lands within inches of sideline\nOpponent stretches, floating defensive reply\nPlayer steps in for put-away winner",
        ],
      },
    ],
  power: [
    {
      min: 0,
      max: 6,
      name: "Unstable",
      process: [
        "First serve speed and spin are repeatable under pressure",
        "Clear identity between flat, slice, and kick serves",
        "Can locate wide, body, and T on both sides with intention",
        "Toss location is stable and supports disguise",
        "Maintains balance and extension through contact",
        "Second serve has shape, height, and margin — not just safety",
        "Can stack 3–5 high-quality service points in a row",
        "Serve patterns are intentional (serve +1 is planned)",
      ],
      breakdown: [
        "Breaks under sustained scoreboard or return pressure",
        "Long deuce games with repeated second serves",
        "Opponent aggressively attacking second serve",
        "Fatigue affecting leg drive and toss consistency",
        "Deliberate max-power serving sequences",
        "Breakdowns are brief and self-corrected.",
      ],
      outcomes: [
        "Slight reduction in first serve percentage",
        "Occasional second serve landing shorter in the box",
        "One over-press first serve miss",
        "Minor toss drift leading to slight contact inconsistency",
        "But recalibration occurs quickly; momentum rarely collapses.",
      ],
      refuses: [
        "Double faults in clusters under routine pressure",
        "Second serve that sits attackable without shape",
        "Predictable serve direction patterns",
      ],
      anchors: [
        "Game at 4–4. Hits wide slice in deuce court, forces return 3–4 feet behind baseline and finishes within two balls",
        "Kicks second serve above shoulder height and neutralizes aggressive returner",
      ],
    },
    {
      min: 7,
      max: 12,
      name: "Conditional",
      process: ["Generates pace in controlled reps or feeding drills"],
      breakdown: ["Cannot access pace reliably in match play or under pressure"],
      refuses: ["Not repeatable on demand in points"],
      outcomes: ["Occasional pace in practice; unreliable in matches"],
      anchors: ["Pace appears during basket feeding", "Fails to reproduce in live points"],
    },
    {
      min: 31,
      max: 40,
      name: "Tour Challenger",
      process: [
        "First serve speed and spin are repeatable at near-max or elite pace",
        "Can disguise flat, slice, and kick serves effectively",
        "Depth consistently lands within 1–3 feet of the service box line",
        "Directional choices are executed late to mask intention",
        "Can stack 8–12 high-quality serves in a row",
        "Balance and leg drive preserved through full extension",
        "Minimal shot-to-shot variance; process is suffocating and repeatable",
      ],
      breakdown: [
        "Breaks only under exceptional circumstances or extreme physical fatigue",
        "Opponent consistently anticipates spin or location perfectly",
        "Rare timing or contact point slips",
      ],
      outcomes: [
        "Slightly slower or shorter first serve on rare lapses",
        "Rare over-hit second serves; immediate recovery for follow-up shot",
        "Serve remains a consistent weapon throughout; momentum almost never swings from a single lapse",
      ],
      refuses: [
        "Repeated double faults under normal conditions",
        "Loss of serve depth under neutral conditions",
      ],
      anchors: [
        "Service game at 4–4. Hits 6 high-speed first serves; opponent misjudges placement and player finishes with elite precision",
        "Tour Elite: first serve speed and spin are at elite max pace; disguise and placement are near-perfect",
      ],
    },
    {
      min: 41,
      max: 50,
      name: "Tour Elite",
      process: [
        "First serve speed and spin are repeatable at near-max or elite pace",
        "Can disguise flat, slice, and kick serves effectively",
        "Depth consistently lands within 1–3 feet of the service box line",
        "Directional choices are executed late to mask intention",
        "Can stack 8–12 high-quality serves in a row",
        "Balance and leg drive preserved through full extension",
        "Minimal shot-to-shot variance; process is suffocating and repeatable",
      ],
      breakdown: [
        "Breaks only under exceptional circumstances or extreme physical fatigue",
        "Opponent consistently anticipates spin or location perfectly",
        "Rare timing or contact point slips",
      ],
      outcomes: [
        "Slightly slower or shorter first serve on rare lapses",
        "Rare over-hit second serves; immediate recovery for follow-up shot",
        "Serve remains a consistent weapon throughout; momentum almost never swings from a single lapse",
      ],
      refuses: [
        "Repeated double faults under normal conditions",
        "Loss of serve depth under neutral conditions",
      ],
      anchors: [
        "Service game at 4–4. Hits 6 high-speed first serves; opponent misjudges placement and player finishes with elite precision",
        "Tour Elite: first serve speed and spin are at elite max pace; disguise and placement are near-perfect",
      ],
    },
    {
      min: 13,
      max: 24,
      name: "Competitive",
      process: ["Power is available and controlled in matches"],
      breakdown: ["Maintains power without a spike in service errors; however, overuse or forced pace can still increase error risk."],
      refuses: ["Does not trade control for raw pace"],
      outcomes: ["Creates pressure through controlled pace"],
      anchors: ["Sustains racquet speed in matches", "Creates pressure without frequent errors"],
    },
    {
      min: 25,
      max: 30,
      name: "Advanced / Pro-Track",
      process: ["Scales power deliberately by score and opponent"],
      breakdown: ["Preserves placement and control when increasing pace, but may see occasional timing slips when pushing for top pace."],
      refuses: ["Does not sacrifice placement for pace"],
      outcomes: ["Controlled winners from intentional power"],
      anchors: ["Deliberate pace changes by situation", "Consistent winners from purposefully hit serves"],
    },
    {
      min: 31,
      max: 40,
      name: "Tour Challenger",
      process: ["Power is consistently weaponized while preserving disguise"],
      breakdown: ["Elite pace maintained with negligible loss of control, yet in rare moments of extreme fatigue control may slightly drop."],
      refuses: ["Does not lose disguise or accuracy when hitting hard"],
      outcomes: ["Routinely creates openings with pace"],
      anchors: ["Pace creates direct point wins", "High-speed serves remain accurate and disguised"],
    },
    {
      min: 41,
      max: 50,
      name: "Tour Elite",
      process: ["Power is consistently weaponized while preserving disguise"],
      breakdown: ["Elite pace maintained with negligible loss of control, yet in rare moments of extreme fatigue control may slightly drop."],
      refuses: ["Does not lose disguise or accuracy when hitting hard"],
      outcomes: ["Routinely creates openings with pace"],
      anchors: ["Pace creates direct point wins", "High-speed serves remain accurate and disguised"],
    },
  ],
  accuracy: [
    {
      min: 0,
      max: 6,
      name: "Unstable",
      process: ["Placement lands far from intended targets; aim is inconsistent"],
      breakdown: ["Direction and landing zone vary unpredictably"],
      refuses: ["No reliable targeting ability"],
      outcomes: ["Frequent directional misses; poor serve placement"],
      anchors: ["Ball lands well outside intended zone often", "Direction is unpredictable"],
    },
    {
      min: 7,
      max: 12,
      name: "Conditional",
      process: ["Hits broad zones in controlled settings"],
      breakdown: ["Cannot reliably place to tight targets under match pressure"],
      refuses: ["Cannot hit tight sub-zones consistently"],
      outcomes: ["General area targeting only; inconsistent tight placement"],
      anchors: ["Hits general target areas in feeding", "Fails tight targets in points"],
    },
    {
      min: 13,
      max: 18,
      name: "Functional",
      process: ["Placement holds in balanced situations with usable consistency"],
      breakdown: ["May lose precision under extreme pressure"],
      refuses: ["Not reliably precise in the tightest moments"],
      outcomes: ["Finds targets when setup is correct; occasional misses under stress"],
      anchors: ["Targets hit in routine rallies", "Precision drops on big points"],
    },
    {
      min: 19,
      max: 24,
      name: "Competitive",
      process: ["Placement is reliable in match play and used to construct points"],
      breakdown: ["Sustains placement under typical match pressures; rare drift under extreme fatigue"],
      refuses: ["Not prone to random directional variability"],
      outcomes: ["Consistent directional control; can create angles"],
      anchors: ["Maintains intended target during matches", "Uses placement to open patterns"],
    },
    {
      min: 25,
      max: 30,
      name: "Advanced / Pro-Track",
      process: ["Placement is intentionally varied to create openings while preserving mechanics"],
      breakdown: ["Executes without mechanical compromise when changing targets, but may occasionally miss extremely tight sub-zones under pressure."],
      refuses: ["Does not lose mechanics when varying placement"],
      outcomes: ["Creates space and angles with deliberate targeting"],
      anchors: ["Chooses exact sub-zones intentionally", "Maintains placement under tactical variation"],
    },
    {
      min: 31,
      max: 40,
      name: "Tour Challenger",
      process: ["Placement is instinctive and tactical; sub-zone targeting is routine"],
      breakdown: ["Precision is maintained across contexts; breakdowns are extremely rare, though rare situational factors can still cause an unexpected miss."],
      refuses: ["Placement does not degrade under pressure"],
      outcomes: ["Elite-level precision that manipulates opponent positioning"],
      anchors: ["Regularly hits sub-zone targets", "Placement defines rally construction"],
    },
    {
      min: 41,
      max: 50,
      name: "Tour Elite",
      process: ["Placement is instinctive and tactical; sub-zone targeting is routine"],
      breakdown: ["Precision is maintained across contexts; breakdowns are extremely rare, though rare situational factors can still cause an unexpected miss."],
      refuses: ["Placement does not degrade under pressure"],
      outcomes: ["Elite-level precision that manipulates opponent positioning"],
      anchors: ["Regularly hits sub-zone targets", "Placement defines rally construction"],
    },
  ],
  spin: [
    {
      min: 0,
      max: 6,
      name: "Unstable",
      process: ["No consistent rotation at contact; spin is accidental or absent"],
      breakdown: ["Trajectory and margin are unpredictable due to lack of spin control"],
      refuses: ["Cannot use spin to manage depth or margin"],
      outcomes: ["Flat or accidental contact; inconsistent depth"],
      anchors: ["Spin absent or accidental on most serves", "Trajectory lacks reliable shape"],
    },
    {
      min: 7,
      max: 12,
      name: "Conditional",
      process: ["Produces spin in controlled reps but struggles in live play"],
      breakdown: ["Cannot regulate depth or shape reliably under match pressure"],
      refuses: ["Cannot depend on spin to shape points in matches"],
      outcomes: ["Spin appears in drills; inconsistent in points"],
      anchors: ["Spin present in feeding drills", "Spin degrades in live points"],
    },
    {
      min: 13,
      max: 18,
      name: "Functional",
      process: ["Uses spin intentionally to manage depth and margin in many reps"],
      breakdown: ["Execution can wobble under tight pressure"],
      refuses: ["Spin is not consistently stable in the tightest moments"],
      outcomes: ["Manages depth and shape with spin in routine play"],
      anchors: ["Regular topspin or slice used to control depth", "Shape reliable in most reps"],
    },
    {
      min: 19,
      max: 24,
      name: "Competitive",
      process: ["Spin reliably shapes serve patterns and supports tactical play"],
      breakdown: ["Sustains spin shape and depth through typical match pressures"],
      refuses: ["Spin does not randomly fail in match play"],
      outcomes: ["Consistent shape and depth that aid neutralizing or attacking"],
      anchors: ["Spin consistently shapes trajectory in matches", "Uses spin to open angles"],
    },
    {
      min: 25,
      max: 30,
      name: "Advanced / Pro-Track",
      process: ["Varies spin deliberately to manipulate timing, depth and opponent movement"],
      breakdown: ["No mechanical compromise when varying spin; rare loss only with extreme fatigue"],
      refuses: ["Spin variation does not cause breakdowns"],
      outcomes: ["Shapes opponent movement and timing with planned spin changes"],
      anchors: ["Deliberate spin variation by intent", "Spin disguises intended depth/shape"],
    },
    {
      min: 31,
      max: 40,
      name: "Tour Challenger",
      process: ["Spin is disguised, consistent and integrated into intent"],
      breakdown: ["Spin control is effectively automatic; breakdowns negligible, but under injury or severe fatigue spin may lose shape briefly."],
      refuses: ["Spin does not reveal intent or degrade under pressure"],
      outcomes: ["Elite spin mastery used to control opponent positioning and disguise intent"],
      anchors: ["Spin used to mask serve intent", "Consistent spin regardless of pace or context"],
    },
    {
      min: 41,
      max: 50,
      name: "Tour Elite",
      process: ["Spin is disguised, consistent and integrated into intent"],
      breakdown: ["Spin control is effectively automatic; breakdowns negligible, but under injury or severe fatigue spin may lose shape briefly."],
      refuses: ["Spin does not reveal intent or degrade under pressure"],
      outcomes: ["Elite spin mastery used to control opponent positioning and disguise intent"],
      anchors: ["Spin used to mask serve intent", "Consistent spin regardless of pace or context"],
    },
  ],
  technique: [
    {
      min: 0,
      max: 6,
      name: "Unstable",
      process: ["Timing, sequencing or grip change between reps; motion is inefficient"],
      breakdown: ["Motion inefficient; recovery suffers and consistency collapses"],
      refuses: ["Cannot demonstrate repeatable preparation or efficient recovery"],
      outcomes: ["Inefficient serves with slow recovery and high error rates"],
      anchors: ["Grip/timing change serve-to-serve", "Poor recovery after serve"],
    },
    {
      min: 7,
      max: 12,
      name: "Conditional",
      process: ["Mechanics hold in calm reps but break on the move or under pressure"],
      breakdown: ["Fails when rushed, moving, or under scoring pressure"],
      refuses: ["Not consistently efficient during match movement"],
      outcomes: ["Functional mechanics in controlled settings; degrades in live play"],
      anchors: ["Mechanics ok in feeding; break when moving", "Timing shifts under stress"],
    },
    {
      min: 13,
      max: 18,
      name: "Functional",
      process: ["Repeatable toss, coordinated leg drive and efficient follow-through"],
      breakdown: ["Some instability under extreme pressure or prolonged fatigue"],
      refuses: ["Does not lose basic coordination in routine play"],
      outcomes: ["Consistent contact and acceptable recovery in most reps"],
      anchors: ["Early preparation and coordinated leg drive", "Consistent follow-through in practice"],
    },
    {
      min: 19,
      max: 24,
      name: "Competitive",
      process: ["Precise toss, effective leg drive and coordinated kinetic chain under match conditions"],
      breakdown: ["Maintains coordinated mechanics through typical match pressures; rare mechanical slips under extreme fatigue"],
      refuses: ["Does not show gross mechanical errors during matches"],
      outcomes: ["Consistent serves under pressure with efficient recovery"],
      anchors: ["Compact preparation with reliable leg drive", "Fast recovery and consistent sequencing"],
    },
    {
      min: 25,
      max: 30,
      name: "Advanced / Pro-Track",
      process: ["Toss precision and efficient kinetic chain use with minimal wasted motion"],
      breakdown: ["Preserves economy and recovery even when increasing quality; breaks only under injury-level fatigue"],
      refuses: ["Does not waste energy when serving aggressively"],
      outcomes: ["Powerful, economical serves with quick recovery and consistency"],
      anchors: ["Optimized kinetic chain use", "Minimal excess motion while preserving power"],
    },
    {
      min: 31,
      max: 40,
      name: "Tour Challenger",
      process: ["Mechanics are finely tuned, automated and economical across serve types"],
      breakdown: ["Execution is efficient, repeatable and weaponized; breakdowns are extremely rare, however extreme fatigue or acute injury can cause mechanical slips."],
      refuses: ["Mechanics do not vary across serve types or under pressure"],
      outcomes: ["Automatic, elite-level serving with immediate recovery"],
      anchors: ["Mechanics identical across serve types", "Effortless recovery and consistent sequencing"],
    },
    {
      min: 41,
      max: 50,
      name: "Tour Elite",
      process: ["Mechanics are finely tuned, automated and economical across serve types"],
      breakdown: ["Execution is efficient, repeatable and weaponized; breakdowns are extremely rare, however extreme fatigue or acute injury can cause mechanical slips."],
      refuses: ["Mechanics do not vary across serve types or under pressure"],
      outcomes: ["Automatic, elite-level serving with immediate recovery"],
      anchors: ["Mechanics identical across serve types", "Effortless recovery and consistent sequencing"],
    },
  ],
};

const commonBands: Record<string, Band[]> = {
  consistency: [
    {
      min: 0,
      max: 6,
      name: "Unstable",
      description: "Produces unpredictable results: toss, contact and timing shift serve-to-serve, causing frequent missed serves or soft returns.",
      anchors: ["Toss/contact vary visibly", "Frequent missed serves or sitters", "Coach cannot predict serve outcome from setup"],
    },
    {
      min: 7,
      max: 12,
      name: "Conditional",
      description: "Routine repeats in calm reps but breaks under scoring pressure, pace, or fatigue.",
      anchors: ["Repeatable in warm-up or feeding", "Rhythm collapses in live points", "Toss/contact drift during pressure"],
    },
    {
      min: 13,
      max: 18,
      name: "Functional",
      description: "Routine repeats in practice and most match moments; visible breakdowns occur during high-pressure points or long service games.",
      anchors: ["Predictable serve shape most attempts", "Starts points reliably in routine play", "Breakdowns limited to pressure moments"],
    },
    {
      min: 19,
      max: 24,
      name: "Competitive",
      description: "Routine holds under match pressure: toss and contact are consistent and service errors are rare. Breaks under strong, well-executed pressure.",
      anchors: ["Motion nearly identical across games", "Maintains quality in pressure points", "Few double faults or mis-contacts"],
    },
    {
      min: 25,
      max: 30,
      name: "Advanced / Pro-Track",
      description: "Routine remains stable across long matches and tactical shifts; player varies serve type without mechanical breakdown. Breaks under sustained or layered pressure.",
      anchors: ["Stable deep into sessions", "Changes serve type without visible loss of mechanics", "Consistent toss/rhythm under fatigue"],
    },
    {
      min: 31,
      max: 40,
      name: "Tour Challenger",
      description: "Routine is automated: identical preparation across serve types, subtle variation for disguise, and consistent outcomes regardless of context. Breaks only under exceptional execution.",
      anchors: ["Different serves originate from same routine", "Opponents cannot read serve type from setup", "Mechanical execution appears automatic"],
    },
    {
      min: 41,
      max: 50,
      name: "Tour Elite",
      description: "Routine is automated: identical preparation across serve types, subtle variation for disguise, and consistent outcomes regardless of context. Breaks only under exceptional execution.",
      anchors: ["Different serves originate from same routine", "Opponents cannot read serve type from setup", "Mechanical execution appears automatic"],
    },
  ],
  power: [
    {
      min: 0,
      max: 6,
      name: "Unstable",
      description: "Attempts at pace destroy balance or timing: racquet speed and contact point vary and produce errors rather than winners.",
      anchors: ["Swinged-for power causes mistimed contact", "Inconsistent racquet speed", "Few or no successful aggressive serves"],
    },
    {
      min: 7,
      max: 12,
      name: "Conditional",
      description: "Player can generate pace in controlled reps but cannot access it reliably during match-play or under pressure.",
      anchors: ["Pace appears in feeding drills", "Not repeatable in point play", "Power attempts raise error rate under stress"],
    },
    {
      min: 13,
      max: 18,
      name: "Functional",
      description: "Adds pace on readable balls and short opportunities; winners occur occasionally when set-up is favorable.",
      anchors: ["Produces pace on short/weak returns", "Occasional service winners", "Manageable risk when aggressive"],
    },
    {
      min: 19,
      max: 24,
      name: "Competitive",
      description: "Power is available and controlled in match situations, producing consistent pressure without a spike in errors. Breaks under strong, well-executed pressure.",
      anchors: ["Sustained racquet speed in matches", "Creates pressure without frequent errors", "Uses pace tactically"],
    },
    {
      min: 25,
      max: 30,
      name: "Advanced / Pro-Track",
      description: "Player scales power deliberately by score, opponent and serve type while preserving control and placement. Breaks under sustained or layered pressure.",
      anchors: ["Scales pace by situation", "Controlled winners from power", "Maintains placement with pace"],
    },
    {
      min: 31,
      max: 40,
      name: "Tour Challenger",
      description: "Power is weaponized: pace consistently wins points while accuracy and disguise remain intact. Breaks only under exceptional execution.",
      anchors: ["Power routinely creates openings", "Elite-level pace with maintained control", "Uses pace as primary tactic when needed"],
    },
    {
      min: 41,
      max: 50,
      name: "Tour Elite",
      description: "Power is weaponized: pace consistently wins points while accuracy and disguise remain intact. Breaks only under exceptional execution.",
      anchors: ["Power routinely creates openings", "Elite-level pace with maintained control", "Uses pace as primary tactic when needed"],
    },
  ],
  accuracy: [
    {
      min: 0,
      max: 6,
      name: "Unstable",
      description: "Placement is inconsistent: the ball frequently lands far from intended targets and direction varies unpredictably.",
      anchors: ["No clear targeting", "High directional variability", "Misses intended zones often"],
    },
    {
      min: 7,
      max: 12,
      name: "Conditional",
      description: "Player can hit broad zones but cannot reliably place to tight targets under match conditions.",
      anchors: ["Hits general areas only", "Fails to hit tight targets", "Needs ideal setup for precision"],
    },
    {
      min: 13,
      max: 18,
      name: "Functional",
      description: "Placement holds in balanced situations; player finds targets when set-up is correct but may lose it under extreme pressure.",
      anchors: ["Targets hit when balanced", "Usable placement in rallies", "Occasional misses under pressure"],
    },
    {
      min: 19,
      max: 24,
      name: "Competitive",
      description: "Placement is reliable in matches: player hits intended areas consistently and uses placement to construct points.",
      anchors: ["Targets maintained during match play", "Creates angles with placement", "Consistent directional control"],
    },
    {
      min: 25,
      max: 30,
      name: "Advanced / Pro-Track",
      description: "Placement is intentionally varied to create openings and is executed without mechanical breakdown. Breaks under sustained or layered pressure.",
      anchors: ["Chooses exact targets", "Creates space with placement", "High repeatability of targeted serves"],
    },
    {
      min: 31,
      max: 40,
      name: "Tour Challenger",
      description: "Placement is instinctive and tactical: player consistently hits sub-zones to manipulate opponent positioning. Breaks only under exceptional execution.",
      anchors: ["Manipulates opponent positioning", "Elite-level precision", "Targets change with intent"],
    },
    {
      min: 41,
      max: 50,
      name: "Tour Elite",
      description: "Placement is instinctive and tactical: player consistently hits sub-zones to manipulate opponent positioning. Breaks only under exceptional execution.",
      anchors: ["Manipulates opponent positioning", "Elite-level precision", "Targets change with intent"],
    },
  ],
  spin: [
    {
      min: 0,
      max: 6,
      name: "Unstable",
      description: "Spin production is accidental or absent: contact does not impart consistent rotation and trajectory is unpredictable.",
      anchors: ["No consistent rotation", "Flat or accidental spin", "Unreliable ball trajectory"],
    },
    {
      min: 7,
      max: 12,
      name: "Conditional",
      description: "Player can produce spin in controlled reps but cannot regulate depth or shape reliably in live play.",
      anchors: ["Spin appears in drills", "Depth/shape vary in points", "Cannot regulate spin under pressure"],
    },
    {
      min: 13,
      max: 18,
      name: "Functional",
      description: "Spin is used intentionally to manage depth and margin, though execution can wobble under pressure.",
      anchors: ["Uses spin to increase margin", "Controls depth in practice", "Some variability in tight moments"],
    },
    {
      min: 19,
      max: 24,
      name: "Competitive",
      description: "Spin reliably shapes patterns and supports both neutral and offensive play in matches. Breaks under strong, well-executed pressure.",
      anchors: ["Spin supports tactical patterns", "Consistent shape and depth", "Used to neutralize or attack"],
    },
    {
      min: 25,
      max: 30,
      name: "Advanced / Pro-Track",
      description: "Player varies spin deliberately to manipulate opponent timing and depth without mechanical compromise. Breaks under sustained or layered pressure.",
      anchors: ["Deliberate spin variation", "Shapes opponent movement", "High control over spin depth/shape"],
    },
    {
      min: 31,
      max: 40,
      name: "Tour Challenger",
      description: "Spin is an elite tool: disguised and consistent, used to control opponent positioning and disguise intent. Breaks only under exceptional execution.",
      anchors: ["Spin used for disguise", "Controls opponent movement", "Elite-level spin mastery"],
    },
    {
      min: 41,
      max: 50,
      name: "Tour Elite",
      description: "Spin is an elite tool: disguised and consistent, used to control opponent positioning and disguise intent. Breaks only under exceptional execution.",
      anchors: ["Spin used for disguise", "Controls opponent movement", "Elite-level spin mastery"],
    },
  ],
  technique: [
    {
      min: 0,
      max: 6,
      name: "Unstable",
      description: "Mechanical execution varies significantly between reps: timing, sequencing or grips change and energy is wasted.",
      anchors: ["Inconsistent grips/timing", "Visible sequencing errors", "High energy waste"],
    },
    {
      min: 7,
      max: 12,
      name: "Conditional",
      description: "Mechanics hold in calm reps but break down when rushed, under pressure, or when movement is required.",
      anchors: ["Holds under calm conditions", "Breaks when rushed", "Efficiency drops under stress"],
    },
    {
      min: 13,
      max: 18,
      name: "Functional",
      description: "Mechanics are repeatable across sessions and allow reliable recovery and shot production in routine match play.",
      anchors: ["Repeatable sequencing", "Reasonable efficiency", "Consistent recovery"],
    },
    {
      min: 19,
      max: 24,
      name: "Competitive",
      description: "Technique holds under match stress with efficient sequencing and quick recovery, supporting tactical play. Breaks under strong, well-executed pressure.",
      anchors: ["Efficient under pressure", "Good sequencing", "Quick recovery"],
    },
    {
      min: 25,
      max: 30,
      name: "Advanced / Pro-Track",
      description: "Technique is economical and stable under tactical stress, with minimal wasted motion and consistent execution. Breaks under sustained or layered pressure.",
      anchors: ["Economical movement", "Stable under tactics", "Optimized sequencing"],
    },
    {
      min: 31,
      max: 40,
      name: "Tour Challenger",
      description: "Technique is automated and invisible: execution is consistent, efficient and repeatable under all conditions. Breaks only under exceptional execution.",
      anchors: ["Automatic technique", "Minimal waste", "Effortless execution"],
    },
    {
      min: 41,
      max: 50,
      name: "Tour Elite",
      description: "Technique is automated and invisible: execution is consistent, efficient and repeatable under all conditions. Breaks only under exceptional execution.",
      anchors: ["Automatic technique", "Minimal waste", "Effortless execution"],
    },
  ],
};

import anchors from './anchorKey';

const referenceKey: Record<string, Record<string, Band[]>> = {
  serve,
  // Return uses most common bands but return consistency has return-specific descriptions
  return: {
    consistency: [
      {
        min: 0,
        max: 6,
        name: "Unstable",
        process: [
          "Inconsistent preparation",
          "Contact point fluctuates",
          "Balance frequently compromised",
          "Ball height and depth vary widely",
          "Can produce a good shot but not predictably",
        ],
        breakdown: [
          "Any directional change",
          "Any increase in pace",
          "Movement while hitting",
          "Slight time pressure",
          "Breakdown threshold is very low",
        ],
        outcomes: [
          "Ball into net or long",
          "Mishits",
          "Short balls",
          "Loss of rally within 1–3 shots",
          "Points end quickly",
        ],
        refuses: [],
        anchors: ["Late to ball", "Weak contact", "Poor footwork"],
        description: "Quality is accidental more than constructed.",
      },
      { min: 7, max: 12, name: "Conditional", description: "Reliable in controlled settings; breaks down under pace or movement", anchors: ["Works in calm returns", "Breaks under pace", "Needs predictable feed"] },
      { min: 13, max: 18, name: "Functional", description: "Consistently gets returns in play vs peers; depth and direction vary under pressure", anchors: ["Gets returns back","Depth varies under pressure","Can reset rallies"] },
      { min: 19, max: 24, name: "Competitive", description: "Return reliability holds in match play and under pressure. Breaks under strong, well-executed pressure.", anchors: ["Neutralizes serve regularly","Maintains depth","Creates chances to attack"] },
      { min: 25, max: 30, name: "Advanced / Pro-Track", description: "Maintains consistency under pace, movement, and fatigue", anchors: ["Anticipates patterns","Consistent under pace","High-level reaction"] },
      { min: 31, max: 40, name: "Tour Challenger", description: "Consistency is assumed; outcomes driven by intent", anchors: ["Elite anticipation","Automatic returns","Controls direction under pressure"] },
      { min: 41, max: 50, name: "Tour Elite", description: "Consistency is assumed; outcomes driven by intent", anchors: ["Elite anticipation","Automatic returns","Controls direction under pressure"] },
    ],
    power: commonBands.power,
    accuracy: commonBands.accuracy,
    spin: commonBands.spin,
    technique: commonBands.technique,
    overall: [
      {
        min: 0,
        max: 6,
        name: "Unstable",
        process: [
          "Late or inconsistent preparation",
          "Contact timing drifts",
          "Poor footwork and balance",
          "Depth and direction vary unpredictably",
        ],
        breakdown: [
          "Any pace increase",
          "Directional change",
          "Pressure on placement",
          "Movement while returning",
        ],
        outcomes: ["Shallow returns", "Missed targets", "Gives easy points", "Rallies end quickly"],
        refuses: [],
        anchors: ["Weak footwork", "Missed contact", "Gives easy points"],
        description: "Quality is accidental more than constructed.",
      },
      { min: 7, max: 12, name: "Conditional", description: "Can produce playable returns in calm settings but lacks consistent depth, placement, or power under pressure.", anchors: ["Playable in calm settings","Struggles under pressure","Depth inconsistent"] },
      { min: 13, max: 18, name: "Functional", description: "Regularly gets returns back into play with workable depth and direction; return quality may vary in tense situations.", anchors: ["Gets returns in play","Works vs peers","Occasional misses under stress"] },
      { min: 19, max: 24, name: "Competitive", description: "Reliable returns in match play that neutralize many serves and create chances to initiate offense. Breaks under strong, well-executed pressure.", anchors: ["Neutralizes serve","Creates offense","Consistent depth"] },
      { min: 25, max: 30, name: "Advanced / Pro-Track", description: "Anticipates serve patterns, consistently returns with depth and intent, and often sets up tactical advantage.", anchors: ["Anticipates patterns","Targets placement","Creates tactical chances"] },
      { min: 31, max: 40, name: "Tour Challenger", description: "Elite returner: reads serves, redirects pace and placement to seize control and generate immediate pressure on serve.", anchors: ["Reads serve instinctively","Redirects pace","Immediate pressure on serve"] },
      { min: 41, max: 50, name: "Tour Elite", description: "Elite returner: reads serves, redirects pace and placement to seize control and generate immediate pressure on serve.", anchors: ["Reads serve instinctively","Redirects pace","Immediate pressure on serve"] },
    ],
  },
  forehand: {
    ...commonBands,
    overall: [
      {
        min: 0,
        max: 6,
        name: "Unstable",
        description: "Quality is accidental more than constructed.",
        process: [
          "Preparation is late or inconsistent",
          "Unit turn may be incomplete or absent",
          "Grip shifts unintentionally between balls",
          "Spacing to the ball is inconsistent",
          "Contact point fluctuates in front and behind the body",
          "Balance frequently compromised at impact",
          "Swing path varies widely from rep to rep",
          "Can produce a clean forehand occasionally, but not predictably",
          "Quality is accidental more than constructed",
        ],
        breakdown: [
          "Any directional change",
          "Any increase in pace",
          "Balls outside ideal strike zone",
          "Movement while hitting",
          "Slight time pressure",
          "Breakdown threshold is very low",
        ],
        outcomes: [
          "Ball into the net or long",
          "Frequent mishits or framed balls",
          "Short balls landing inside the service box",
          "Floaty contact with no depth",
          "Loss of rally within 1–3 shots",
          "Points end quickly or control is immediately surrendered",
        ],
        refuses: [],
        anchors: [
          "Rally at 2–2. Player: Misses first forehand into the net OR Pushes forehand softly down the middle",
          "Opponent steps in and attacks OR Hits one clean forehand then opponent mishits next ball",
          "Point won through opponent error or a single clean contact, not through repeatable forehand structure, depth, or directional control.",
        ],
      },
      {
        min: 7,
        max: 12,
        name: "Conditional",
        description: "Can rally and produce quality within a comfort zone; breaks occur when difficulty or pace increases.",
        process: [
          "Preparation and unit turn are generally reliable for moderate-paced rallies",
          "Footwork allows positioning behind the ball most of the time",
          "Can rally 4–6 balls crosscourt or down the line with moderate depth",
          "Contact point is generally consistent in front of the body",
          "Quality depends on pace and direction within comfort zone",
          "Process holds if conditions are comfortable",
        ],
        breakdown: [
          "Opponent increases pace or hits deeper balls",
          "Forced wide or short balls requiring adjustment",
          "Direction changes under movement",
          "Slight fatigue or distraction",
          "Player attempts aggressive angle or topspin beyond stability",
        ],
        outcomes: [
          "Net errors when trying to redirect pace",
          "Long balls when attempting depth or spin",
          "Off-balance or rushed forehand",
          "Short or floaty ball due to over-accelerated swing",
          "Rallies often end because the player forces instead of constructing the point",
        ],
        refuses: [],
        anchors: [
          "Rally at 3–3. Opponent hits a mid-depth crosscourt ball; player steps in and executes a firm forehand crosscourt",
          "Next ball comes slightly faster or wider; player attempts a more aggressive angle and ball drifts long or clips net",
          "Points won off forehand are usually because opponent misjudges or because the forehand is executed within comfort zone",
        ],
      },
      {
        min: 13,
        max: 18,
        name: "Functional",
        description: "Forehand is a dependable rally tool with usable power and placement; effectiveness can vary in tight match moments.",
        process: [
          "Preparation and unit turn are consistent and reliable under pressure",
          "Footwork allows positioning behind the ball for moderate to aggressive rallies",
          "Can sustain 6–10 forehands crosscourt or down the line with controlled depth",
          "Contact point is consistently in front of the body",
          "Can defend, redirect pace, and begin constructing points intentionally",
          "Quality is repeatable and allows follow-up control",
        ],
        breakdown: [
          "Opponent increases pace or hits deeper balls",
          "Wide, short, or angled balls requiring adjustment",
          "Rapid direction changes",
          "Slight fatigue late in sets",
          "Player attempts aggressive angles, topspin, or placement beyond stability",
        ],
        outcomes: [
          "Net errors or short balls under stress",
          "Depth reduces, giving opponent easier options",
          "Defensive or floaty replies",
          "Opponent gains control, but collapse is not immediate",
        ],
        refuses: [],
        anchors: [
          "Rally at 4–4. Player trades 5 crosscourt forehands, changes direction safely, opponent defends short, player steps in and finishes",
          "Point won through controlled rally + deliberate direction change",
        ],
      },
      {
        min: 19,
        max: 24,
        name: "Competitive",
        description: "Delivers controlled aggression: consistent timing, tactical power and placement that win points in matches. Breaks under strong, well-executed pressure.",
        process: [
          "Preparation is early and consistent under match pressure",
          "Spacing is reliable — contact is typically out in front",
          "Swing path and tempo hold up during neutral and moderate pressure rallies",
          "Can sustain 4–8 ball crosscourt exchanges without breakdown",
          "Directional control is intentional",
          "Can accelerate when a shorter ball appears",
        ],
        breakdown: [
          "Breaks under strong, well-executed pressure",
          "Heavy pace into the forehand corner",
          "Sudden redirection under time compression",
          "High, heavy spin pushing contact back",
          "Fatigue in extended exchanges",
        ],
        outcomes: [
          "Low forehand error rate overall",
          "Occasional shorter neutral ball",
          "Attackable mid-court ball appears",
          "Rally control temporarily shifts",
        ],
        refuses: [],
        anchors: [
          "Rally at 4–4. Competitive player sustains solid crosscourt forehands, maintains depth and shape, steps in and finishes",
          "Point won through pattern tolerance + opportunity recognition",
        ],
      },
      {
        min: 25,
        max: 30,
        name: "Advanced / Pro-Track",
        description: "Combines refined technique, directional control, and varied spin to create and finish attacking patterns.",
        process: [
          "Consistent depth within 2–4 feet of the baseline",
          "Heavy ball quality (pace + spin) is repeatable",
          "Can change direction without significant drop in speed",
          "Maintains spacing and balance under high pace",
          "Can flatten, roll, or drive intentionally",
          "Recovers quickly after aggressive forehands",
        ],
        breakdown: [
          "Breaks under sustained defensive stress or extreme pace",
          "Repeated heavy crosscourt exchanges",
          "Being rushed inside baseline",
          "Fatigue affecting leg load and spacing",
        ],
        outcomes: [
          "Slight depth reduction",
          "One shorter ball during prolonged rally",
          "Minor timing slip on direction change",
          "Occasional over-press on inside forehand",
        ],
        refuses: [],
        anchors: [
          "Neutral rally. Advanced player trades 4 heavy crosscourt balls, changes direction down the line with pace, forces short reply and finishes",
          "Point won through sustained forehand quality + directional stability",
        ],
      },
      {
        min: 31,
        max: 40,
        name: "Tour Challenger",
        description: "High-level weapon: explosive, accurate, and varied forehand that consistently defines rallies and produces winners.",
        process: [
          "Preparation is early, racquet set with consistent backswing",
          "Depth consistently lands 2–4 feet behind baseline",
          "Can generate moderate pace with spin and direction control",
          "Can hit 6–8 consecutive high-quality forehands",
          "Footwork and balance maintained during extended rallies",
          "Able to change direction or height intentionally",
        ],
        breakdown: [
          "Breaks only under strong rallying or high-intensity conditions",
          "Opponent hits sustained pace or spin",
          "Fatigue affects positioning or timing",
        ],
        outcomes: [
          "Slightly shorter or flatter shot under high pace",
          "Occasional mis-hit or defensive response",
          "Recovery into neutral or offensive position is immediate",
        ],
        refuses: [],
        anchors: [
          "Player hits 6 consecutive deep forehands",
          "Moves opponent laterally 2–3 feet behind baseline and finishes inside court",
        ],
      },
      {
        min: 41,
        max: 50,
        name: "Tour Elite",
        description: "Forehand is a dominant weapon, continuously pressuring opponent with minimal variance and elite repeatability.",
        process: [
          "Racquet preparation is instantaneous and precise",
          "Depth consistently within 1–3 feet of the baseline",
          "Pace, spin, and angle maintained at near-max level",
          "Can hit 8–12 consecutive high-quality forehands",
          "Footwork, balance, and weight transfer preserved under full-speed conditions",
          "Direction, height, and spin changes executed late to disguise intention",
        ],
        breakdown: [
          "Breaks only under exceptional conditions",
          "Extreme fatigue late in long sets",
          "Opponent anticipates spin, pace, or placement perfectly",
        ],
        outcomes: [
          "Slightly shorter or flatter shot under extreme pace",
          "Recovery is immediate",
          "Momentum almost never shifts from a single lapse",
        ],
        refuses: [],
        anchors: [
          "Player hits 8 consecutive deep, heavy forehands at full pace",
          "Changes direction or height at last millisecond to disguise intent and finishes cleanly inside baseline",
        ],
      },
    ],
    technique: [
      {
        min: 0,
        max: 6,
        name: "Unstable",
        process: ["Inconsistent preparation", "Poor weight transfer", "Long, wasteful swings"],
        breakdown: ["Any pace or placement demand", "Movement while hitting", "Sustained pressure"],
        outcomes: ["Low power", "Slow recovery", "Frequent unforced errors"],
        refuses: [],
        anchors: ["Late preparation", "Inefficient weight transfer", "Long swing"],
        description: "Quality is accidental more than constructed.",
      },
      { min: 7, max: 12, name: "Conditional", description: "Preparation is sometimes adequate but breaks under pressure; weight transfer and timing can be inefficient.", anchors: ["Inconsistent prep","Breaks under pressure","Timing issues"] },
      { min: 13, max: 18, name: "Functional", description: "Prepares early with solid weight transfer and efficient follow-through, enabling consistent recovery.", anchors: ["Early prep","Solid weight transfer","Efficient recovery"] },
      { min: 19, max: 24, name: "Competitive", description: "Compact preparation, reliable weight transfer, and efficient footwork allow sustained aggression without wasted motion. Breaks under strong, well-executed pressure.", anchors: ["Compact prep","Efficient footwork","Sustained aggression"] },
      { min: 25, max: 30, name: "Advanced / Pro-Track", description: "Maximizes kinetic chain use with minimal excess movement; adjusts swing length for control and efficiency.", anchors: ["Optimized kinetic chain","Minimal excess motion","Adjusts swing length"] },
      { min: 31, max: 40, name: "Tour Challenger", description: "Swing timing, energy use, and recovery are optimized; movement and stroke are economical and effortless.", anchors: ["Optimized timing","Effortless recovery","Economical movement"] },
      { min: 41, max: 50, name: "Tour Elite", description: "Swing timing, energy use, and recovery are optimized; movement and stroke are economical and effortless.", anchors: ["Optimized timing","Effortless recovery","Economical movement"] },
    ],
    
  },
  backhand: {
    consistency: [
      {
        min: 0,
        max: 6,
        name: "Unstable",
        description:
          "Backhand preparation and contact are erratic: timing, grip or footwork vary and defensive shots are often weak or misdirected.",
        anchors: [
          "Contact point and grip change between reps",
          "Footwork arrives late or off-balance frequently",
          "Backhand produces many defensive slices or errors",
        ],
      },
      {
        min: 7,
        max: 12,
        name: "Conditional",
        description:
          "Stroke repeats in calm drills but degrades under pace, movement, or scoring pressure; quality depends on ideal positioning.",
        anchors: [
          "Backhand is reliable in feeding drills",
          "Depth and timing drift during live points",
          "Struggles when stretched or rushed",
        ],
      },
      {
        min: 13,
        max: 18,
        name: "Functional",
        description:
          "Backhand is dependable in practice and most match moments; occasional visible breakdowns occur under high pressure or extended rallies.",
        anchors: [
          "Consistent contact and direction in many reps",
          "Can produce depth and occasional offense when set-up correctly",
          "Errors increase mainly in tense situations",
        ],
      },
      {
        min: 19,
        max: 24,
        name: "Competitive",
        description:
          "Backhand mechanics and footwork hold under match pressure, enabling consistent depth, neutralization or offensive options in rallies.",
        anchors: [
          "Stroke preparation looks consistent across matches",
          "Maintains depth and direction during pressure points",
          "Able to use backhand to create or redirect offense reliably",
        ],
      },
      {
        min: 25,
        max: 30,
        name: "Advanced / Pro-Track",
        description:
          "Backhand remains stable through long matches and tactical shifts; player varies pace, spin or grip without mechanical compromise.",
        anchors: [
          "Backhand structure holds deep into matches",
          "Adjusts pace/spin without loss of mechanics",
          "Footwork and recovery remain efficient under fatigue",
        ],
      },
      {
        min: 31,
        max: 40,
        name: "Tour Challenger",
        description:
          "Backhand is automated: consistent preparation, reliable contact, and subtle variation for disguise and tactical effect across contexts.",
        anchors: [
          "Different backhand looks originate from the same prep",
          "Opponents cannot reliably anticipate outcome from setup",
          "Backhand quality remains unchanged regardless of score or fatigue",
        ],
      },
      {
        min: 41,
        max: 50,
        name: "Tour Elite",
        description:
          "Backhand is automated: consistent preparation, reliable contact, and subtle variation for disguise and tactical effect across contexts.",
        anchors: [
          "Different backhand looks originate from the same prep",
          "Opponents cannot reliably anticipate outcome from setup",
          "Backhand quality remains unchanged regardless of score or fatigue",
        ],
      },
    ],
    overall: [
      {
        min: 0,
        max: 6,
        name: "Unstable",
        process: [
          "Erratic preparation and grip changes",
          "Timing and contact vary between reps",
          "Footwork often arrives late or off-balance",
        ],
        breakdown: [
          "Any increase in pace",
          "Directional changes",
          "Pressure while stretched or on the run",
        ],
        outcomes: ["Weak defensive shots", "Frequent errors", "Slow recovery leading to lost points"],
        refuses: [],
        anchors: ["Erratic preparation", "Weak defensive shots", "Slow recovery"],
        description: "Quality is accidental more than constructed.",
      },
      { min: 7, max: 12, name: "Conditional", description: "Executes usable backhands in calm situations but loses reliability and depth under pressure.", anchors: ["Works calm settings","Loses depth under pressure","Inconsistent offense"] },
      { min: 13, max: 18, name: "Functional", description: "Backhand is consistent for rallies with solid technique and occasional offensive options.", anchors: ["Consistent rally tool","Occasional offense","Reliable technique"] },
      { min: 19, max: 24, name: "Competitive", description: "Compact and reliable backhand that supports aggression and maintains depth under match conditions. Breaks under strong, well-executed pressure.", anchors: ["Compact & reliable","Supports aggression","Maintains depth"] },
      { min: 25, max: 30, name: "Advanced / Pro-Track", description: "Backhand offers tactical variety and dependable power or disguise when needed to finish or set up points.", anchors: ["Tactical variety","Dependable disguise","Finishes points"] },
      { min: 31, max: 40, name: "Tour Challenger", description: "A refined, powerful, and precise backhand that operates as a consistent offensive and defensive tool at elite levels.", anchors: ["Refined & precise","Elite-level tool","Consistent winner"] },
      { min: 41, max: 50, name: "Tour Elite", description: "A refined, powerful, and precise backhand that operates as a consistent offensive and defensive tool at elite levels.", anchors: ["Refined & precise","Elite-level tool","Consistent winner"] },
    ],
    power: commonBands.power,
    accuracy: commonBands.accuracy,
    spin: commonBands.spin,
    technique: [
      {
        min: 0,
        max: 6,
        name: "Unstable",
        process: ["Inconsistent swing mechanics", "Inefficient sequencing", "Variable recovery"],
        breakdown: ["Any pressure on timing", "Faster opponents", "Directional variation"],
        outcomes: ["Mistimed contact", "Low-quality shots", "Slow recovery"],
        refuses: [],
        anchors: ["Inconsistent grips", "Inefficient motion", "Slow recovery"],
        description: "Quality is accidental more than constructed.",
      },
      { min: 7, max: 12, name: "Conditional", description: "Mechanics hold in controlled settings but efficiency degrades under pressure or when stretched.", anchors: ["Holds in calm settings","Degrades under pressure","Efficiency drops when stretched"] },
      { min: 13, max: 18, name: "Functional", description: "Mechanics are repeatable and use efficient core and arm sequencing for reliable recovery.", anchors: ["Repeatable sequencing","Efficient core use","Reliable recovery"] },
      { min: 19, max: 24, name: "Competitive", description: "Compact preparation, strong core engagement, and efficient footwork support consistent, economical execution. Breaks under strong, well-executed pressure.", anchors: ["Compact prep","Strong core engagement","Economical execution"] },
      { min: 25, max: 30, name: "Advanced / Pro-Track", description: "Optimizes kinetic chain and minimal unnecessary movement; adapts grip and swing length efficiently.", anchors: ["Optimizes kinetic chain","Minimal excess motion","Adaptive grip/swing"] },
      { min: 31, max: 40, name: "Tour Challenger", description: "Backhand is delivered with precise timing, efficiency, and effortless recovery under pressure.", anchors: ["Precise timing","Effortless recovery","Elite execution"] },
      { min: 41, max: 50, name: "Tour Elite", description: "Backhand is delivered with precise timing, efficiency, and effortless recovery under pressure.", anchors: ["Precise timing","Effortless recovery","Elite execution"] },
    ],
  },
  volley: {
    consistency: [
      {
        min: 0,
        max: 6,
        name: "Unstable",
        process: ["Poor platform and hand control", "Timing and balance vary", "Recovery is slow"],
        breakdown: ["Off-balance approach", "Pressure on placement or pace", "Movement while volleying"],
        outcomes: ["Missed volleys", "Pop-ups or errors", "Lost net points quickly"],
        refuses: [],
        anchors: ["Poor platform", "Bad hand control", "Frequent errors at net"],
        description: "Quality is accidental more than constructed.",
      },
      { min: 7, max: 12, name: "Conditional", description: "Reliable in controlled settings; breaks down under pace or movement", anchors: ["Works stationary","Breaks when on the move","Timing issues"] },
      { min: 13, max: 18, name: "Functional", description: "Executes volleys reliably; shot outcomes are dependable with predictable miss patterns", anchors: ["Reliable at net","Predictable misses","Good touch"] },
      { min: 19, max: 24, name: "Competitive", description: "Shot reliability holds in match play and under pressure. Breaks under strong, well-executed pressure.", anchors: ["Performs in matches","Finishes short points","Consistent placement"] },
      { min: 25, max: 30, name: "Advanced / Pro-Track", description: "Maintains consistency under pace, movement, and fatigue", anchors: ["Maintains under movement","High touch control","Consistent finishing"] },
      { min: 31, max: 40, name: "Tour Challenger", description: "Consistency is assumed; outcomes driven by intent", anchors: ["Automatic net control","Elite touch & timing","Dominates net exchanges"] },
      { min: 41, max: 50, name: "Tour Elite", description: "Consistency is assumed; outcomes driven by intent", anchors: ["Automatic net control","Elite touch & timing","Dominates net exchanges"] },
    ],
    power: [
      {
        min: 0,
        max: 6,
        name: "Unstable",
        process: ["Attempts to force pace without platform", "Inconsistent punch and timing"],
        breakdown: ["When asked to finish points", "On the move", "Under pace"],
        outcomes: ["Errors when swinging for power", "Loss of control", "Broken net exchanges"],
        refuses: [],
        anchors: ["Swinging causes errors", "Loss of platform", "Poor contact"],
        description: "Quality is accidental more than constructed.",
      },
      { min: 7, max: 12, name: "Conditional", description: "Can add pace occasionally but not on demand; timing and compactness are inconsistent.", anchors: ["Occasional punch","Not repeatable","Timing inconsistent"] },
      { min: 13, max: 18, name: "Functional", description: "Adds compact punch on short or readable balls to finish points or force weak replies.", anchors: ["Compact punch","Finishes short balls","Useful in transition"] },
      { min: 19, max: 24, name: "Competitive", description: "Uses controlled acceleration and placement so volley pace translates into match play advantage. Breaks under strong, well-executed pressure.", anchors: ["Controlled acceleration","Match-effective pace","Places with intent"] },
      { min: 25, max: 30, name: "Advanced / Pro-Track", description: "Scales punch by situation and opponent, mixing soft and firm touches to finish or create openings.", anchors: ["Scales punch","Mixes touch","High control"] },
      { min: 31, max: 40, name: "Tour Challenger", description: "Volley pace is leveraged precisely to create openings and finish points without sacrificing control.", anchors: ["Precise pace control","Finishes reliably","Elite-level placement"] },
      { min: 41, max: 50, name: "Tour Elite", description: "Volley pace is leveraged precisely to create openings and finish points without sacrificing control.", anchors: ["Precise pace control","Finishes reliably","Elite-level placement"] },
    ],
    accuracy: commonBands.accuracy,
    spin: [
      {
        min: 0,
        max: 6,
        name: "Unstable",
        process: ["Inconsistent contact leading to accidental spin", "Lack of repeatable brush or contact angle"],
        breakdown: ["Under pace", "When trying to vary trajectory", "During movement"],
        outcomes: ["Unreliable spin", "Floaty or dead contact", "Inability to shape points"],
        refuses: [],
        anchors: ["Accidental spin", "Floaty contact", "Unstable touch"],
        description: "Quality is accidental more than constructed.",
      },
      { min: 7, max: 12, name: "Conditional", description: "Can apply spin inconsistently; depth and shape often break down.", anchors: ["Inconsistent spin","Depth varies","Shape breaks down"] },
      { min: 13, max: 18, name: "Functional", description: "Uses spin to manage pace and depth; volleys stay controlled under moderate pressure.", anchors: ["Manages pace with spin","Controlled under moderate pressure","Predictable spin"] },
      { min: 19, max: 24, name: "Competitive", description: "Redirects spin intentionally to neutralize or apply pressure; reliable touch in exchanges. Breaks under strong, well-executed pressure.", anchors: ["Redirects spin","Neutralizes opponents","Reliable touch"] },
      { min: 25, max: 30, name: "Advanced / Pro-Track", description: "Varies spin with intent to shape angles, depth, and pace; disguises soft vs firm touch.", anchors: ["Varies spin intentionally","Shapes angles","Disguises contact"] },
      { min: 31, max: 40, name: "Tour Challenger", description: "Elite spin control; uses disguise and redirection to command exchanges under pressure.", anchors: ["Elite spin control","Disguised intent","Commands exchanges"] },
      { min: 41, max: 50, name: "Tour Elite", description: "Elite spin control; uses disguise and redirection to command exchanges under pressure.", anchors: ["Elite spin control","Disguised intent","Commands exchanges"] },
    ],
    technique: [
      {
        min: 0,
        max: 6,
        name: "Unstable",
        process: ["Loose hand control", "Wide backswing", "Poor balance at net"],
        breakdown: ["When moving", "Against pace", "Under finishing pressure"],
        outcomes: ["Failed net entries", "Pop-ups or mis-hits", "Lost short-point exchanges"],
        refuses: [],
        anchors: ["Poor platform", "Loose hand control", "Energy-inefficient swings"],
        description: "Quality is accidental more than constructed.",
      },
      { min: 7, max: 12, name: "Conditional", description: "Can execute simple volleys but timing and economy suffer under pressure or on the move.", anchors: ["Simple volleys only","Timing suffers when moving","Economy degrades under pressure"] },
      { min: 13, max: 18, name: "Functional", description: "Uses a short punch, maintains balance, and recovers with reasonable efficiency.", anchors: ["Short punch","Maintains balance","Reasonable recovery"] },
      { min: 19, max: 24, name: "Competitive", description: "Compact backswing, stable platform, and economical footwork produce reliable, low-effort volleys. Breaks under strong, well-executed pressure.", anchors: ["Compact backswing","Stable platform","Economical footwork"] },
      { min: 25, max: 30, name: "Advanced / Pro-Track", description: "Varies contact and minimal backswing to control pace and angles while conserving energy.", anchors: ["Varies contact","Minimal backswing","Conserves energy"] },
      { min: 31, max: 40, name: "Tour Challenger", description: "Volleys are executed with precise economy of motion, exceptional hand control, and immediate recovery.", anchors: ["Precise economy","Exceptional hand control","Immediate recovery"] },
      { min: 41, max: 50, name: "Tour Elite", description: "Volleys are executed with precise economy of motion, exceptional hand control, and immediate recovery.", anchors: ["Precise economy","Exceptional hand control","Immediate recovery"] },
    ],
    overall: [
      {
        min: 0,
        max: 6,
        name: "Unstable",
        process: ["Inconsistent touch and timing", "Poor platform and balance"],
        breakdown: ["On the move", "When asked to place with precision", "Against fast passes"],
        outcomes: ["Net errors", "Missed placement", "Lost net exchanges"],
        refuses: [],
        anchors: ["Poor touch", "Bad timing", "Frequent net errors"],
        description: "Quality is accidental more than constructed.",
      },
      { min: 7, max: 12, name: "Conditional", description: "Can execute simple volleys but timing and economy break down under pressure or on the move.", anchors: ["Simple volleys only","Timing/economy break down","Struggles when moving"] },
      { min: 13, max: 18, name: "Functional", description: "Reliable net play with reasonable touch and balance; can finish short points when positioned well.", anchors: ["Reasonable touch","Finishes short points","Balanced position"] },
      { min: 19, max: 24, name: "Competitive", description: "Compact, controlled volleys with consistent placement and the ability to finish or redirect pace in matches. Breaks under strong, well-executed pressure.", anchors: ["Consistent placement","Finishes/redirects pace","Compact control"] },
      { min: 25, max: 30, name: "Advanced / Pro-Track", description: "Varied touch and punch, precise placement, and economical motion enable consistent finishing at the net.", anchors: ["Varied touch","Precise placement","Consistent finishing"] },
      { min: 31, max: 40, name: "Tour Challenger", description: "Exceptional volleying: instant control, perfect touch and timing, and the ability to dominate net exchanges.", anchors: ["Instant control","Perfect timing","Dominate net"] },
      { min: 41, max: 50, name: "Tour Elite", description: "Exceptional volleying: instant control, perfect touch and timing, and the ability to dominate net exchanges.", anchors: ["Instant control","Perfect timing","Dominate net"] },
    ],
  },
  overhead: {
    consistency: [
      {
        min: 0,
        max: 6,
        name: "Unstable",
        process: ["Late setup", "Poor footwork", "Inconsistent contact timing"],
        breakdown: ["When rushed", "Against pace", "On the run"],
        outcomes: ["Mistimed overheads", "Misses or weak returns", "Lost finishing opportunities"],
        refuses: [],
        anchors: ["Late setup", "Poor footwork", "Mistimed contact"],
        description: "Quality is accidental more than constructed.",
      },
      { min: 7, max: 12, name: "Conditional", description: "Reliable in controlled settings; breaks down under pace or movement", anchors: ["Works on routine overheads","Breaks under pace","Unstable on the move"] },
      { min: 13, max: 18, name: "Functional", description: "Executes overheads reliably; shot outcomes are dependable with predictable miss patterns", anchors: ["Reliable setup","Predictable misses","Good contact on set-ups"] },
      { min: 19, max: 24, name: "Competitive", description: "Shot reliability holds in match play and under pressure. Breaks under strong, well-executed pressure.", anchors: ["Finishes lobs","Holds under pressure","Consistent contact"] },
      { min: 25, max: 30, name: "Advanced / Pro-Track", description: "Maintains consistency under pace, movement, and fatigue", anchors: ["Maintains on the run","High contact quality","Efficient recovery"] },
      { min: 31, max: 40, name: "Tour Challenger", description: "Consistency is assumed; outcomes driven by intent", anchors: ["Automatic overhead setup","Elite finishing","Near-automatic execution"] },
      { min: 41, max: 50, name: "Tour Elite", description: "Consistency is assumed; outcomes driven by intent", anchors: ["Automatic overhead setup","Elite finishing","Near-automatic execution"] },
    ],
    power: commonBands.power,
    accuracy: commonBands.accuracy,
    spin: commonBands.spin,
    technique: [
      {
        min: 0,
        max: 6,
        name: "Unstable",
        process: ["Long inefficient motion", "Inconsistent setup and footwork"],
        breakdown: ["Against fast feeds", "Under fatigue", "When asked to vary placement"],
        outcomes: ["Low-quality overheads", "High energy cost", "Frequent misses"],
        refuses: [],
        anchors: ["Long motion", "Poor setup", "High energy cost"],
        description: "Quality is accidental more than constructed.",
      },
      { min: 7, max: 12, name: "Conditional", description: "Can complete overheads but setup and economy break down under pressure or when rushed.", anchors: ["Completes when calm","Breaks when rushed","Inefficient under pressure"] },
      { min: 13, max: 18, name: "Functional", description: "Sets up reliably with balanced footing and a compact swing that conserves energy.", anchors: ["Balanced footwork","Compact swing","Conserves energy"] },
      { min: 19, max: 24, name: "Competitive", description: "Efficient positioning, compact backswing, and forward momentum allow powerful, economical overheads. Breaks under strong, well-executed pressure.", anchors: ["Efficient positioning","Compact backswing","Powerful & economical"] },
      { min: 25, max: 30, name: "Advanced / Pro-Track", description: "Optimizes movement into contact and minimizes wasted motion while delivering authoritative overheads.", anchors: ["Optimized movement","Minimal wasted motion","Authoritative contact"] },
      { min: 31, max: 40, name: "Tour Challenger", description: "Overheads are executed with perfect setup, compact mechanics, and maximal efficiency under pressure.", anchors: ["Perfect setup","Compact mechanics","Maximal efficiency"] },
      { min: 41, max: 50, name: "Tour Elite", description: "Overheads are executed with perfect setup, compact mechanics, and maximal efficiency under pressure.", anchors: ["Perfect setup","Compact mechanics","Maximal efficiency"] },
    ],
    overall: [
      {
        min: 0,
        max: 6,
        name: "Unstable",
        process: ["Inconsistent footwork and setup", "Timing drifts on contact"],
        breakdown: ["When rushed", "Against pace", "On the run"],
        outcomes: ["Mistimed overheads", "Errors on finishing attempts"],
        refuses: [],
        anchors: ["Late setup", "Poor footwork", "Mistimed contact"],
        description: "Quality is accidental more than constructed.",
      },
      { min: 7, max: 12, name: "Conditional", description: "Can complete overheads but setup and economy break down under pressure or when rushed." },
      { min: 13, max: 18, name: "Functional", description: "Reliable overheads with generally good setup and contact; effective in routine match situations." },
      { min: 19, max: 24, name: "Competitive", description: "Efficient positioning and compact swing deliver powerful, consistent overheads that finish points. Breaks under strong, well-executed pressure." },
      { min: 25, max: 30, name: "Advanced / Pro-Track", description: "Optimized setup and timing produce authoritative overheads with economy and high success under pressure." },
      { min: 31, max: 40, name: "Tour Challenger", description: "Elite overheads: perfect setup, explosive but controlled contact, and near-automatic finishing capability." },
      { min: 41, max: 50, name: "Tour Elite", description: "Elite overheads: perfect setup, explosive but controlled contact, and near-automatic finishing capability." },
    ],
  },
  movement: {
      overall: [
        {
          min: 0,
          max: 6,
          name: "Unstable",
          process: ["Reactive and slow first step", "Arrives off-balance frequently", "Recovery is poor"],
          breakdown: ["Under fatigue", "When pressured to cover angles", "During extended rallies"],
          outcomes: ["Unable to create space", "Late arrivals leading to errors", "Reduced shot quality"],
          refuses: [],
          anchors: ["Late reactions", "Off-balance arrivals", "Poor recovery"],
          description: "Quality is accidental more than constructed.",
        },
        { min: 7, max: 12, name: "Conditional", description: "Can reach balls but lacks consistent speed, recovery, and spacing; movement degrades under fatigue or pressure.", anchors: ["Reaches but slow","Recovery inconsistent","Degrades with fatigue"] },
        { min: 13, max: 18, name: "Functional", description: "Adequate court coverage and recovery for most rally situations; allows routine shot execution.", anchors: ["Adequate coverage","Balanced recovery","Routine execution"] },
        { min: 19, max: 24, name: "Competitive", description: "Reliable speed, balance, and recovery that supports high-quality shot preparation in match play. Breaks under strong, well-executed pressure.", anchors: ["Reliable speed","Consistent spacing","Good recovery"] },
        { min: 25, max: 30, name: "Advanced / Pro-Track", description: "Proactive anticipation, efficient footwork, and consistent spacing that enable aggressive tactical choices.", anchors: ["Proactive anticipation","Efficient footwork","Enables aggression"] },
        { min: 31, max: 40, name: "Tour Challenger", description: "Automatic, anticipatory movement that maximizes options and executes elite court coverage.", anchors: ["Anticipatory movement","Automatic coverage","Elite options"] },
        { min: 41, max: 50, name: "Tour Elite", description: "Automatic, anticipatory movement that maximizes options and executes elite court coverage.", anchors: ["Anticipatory movement","Automatic coverage","Elite options"] },
      ],
    technique: [
      {
        min: 0,
        max: 6,
        name: "Unstable",
        process: ["Slow first step", "Inconsistent spacing", "Late recoveries"],
        breakdown: ["Against sustained pressure", "When asked to cover wide angles", "Under fatigue"],
        outcomes: ["Missed coverage", "Forced defensive shots", "Points lost quickly"],
        refuses: [],
        anchors: ["Slow/reactive", "Late arrival", "Poor spacing"],
        description: "Quality is accidental more than constructed.",
      },
      { min: 7, max: 12, name: "Conditional", description: "Can reach many balls but movement speed, recovery, and spacing are inconsistent, reducing shot preparation quality.", anchors: ["Reaches inconsistently","Recovery varies","Spacing inconsistent"] },
      { min: 13, max: 18, name: "Functional", description: "Covers the court adequately vs peers and typically arrives balanced with sufficient spacing to execute standard shots.", anchors: ["Adequate coverage","Balanced arrivals","Executes standard shots"] },
      { min: 19, max: 24, name: "Competitive", description: "Moves with reliable speed and balance, consistently arriving in positions that enable high-quality shot execution and effective spacing. Breaks under strong, well-executed pressure.", anchors: ["Reliable speed","Consistent balance","Good spacing"] },
      { min: 25, max: 30, name: "Advanced / Pro-Track", description: "Anticipates and covers court proactively, arriving early with superior spacing to set up aggressive and varied shot options.", anchors: ["Proactive anticipation","Arrives early","Superior spacing"] },
      { min: 31, max: 40, name: "Tour Challenger", description: "Movement is automatic: covers court efficiently, anticipates positioning, and consistently creates ideal spacing to maximize shot choice and execution.", anchors: ["Automatic movement","Perfect spacing","Elite anticipation"] },
      { min: 41, max: 50, name: "Tour Elite", description: "Movement is automatic: covers court efficiently, anticipates positioning, and consistently creates ideal spacing to maximize shot choice and execution.", anchors: ["Automatic movement","Perfect spacing","Elite anticipation"] },
    ],
  },
};

export function normalizeKey(s: string) {
  return String(s || "").trim().toLowerCase();
}

export function getBand(skill: string, component: string, value: number) {
  const sk = normalizeKey(skill);
  const comp = normalizeKey(component);
  const skillEntry = (referenceKey as any)[sk] || (referenceKey as any)[sk.replace(/\s+/g, '')];
  if (!skillEntry) return { name: 'Unknown', description: '' };
  const compMap: Record<string, string> = { c: 'consistency', p: 'power', a: 'accuracy', s: 'spin', t: 'technique' };
  const canonicalComp = compMap[comp] || comp;
  const bands = (skillEntry as any)[comp] || (skillEntry as any)[canonicalComp];
  if (!bands || !Array.isArray(bands)) return { name: 'Unknown', description: '' };
  const vRaw = Number(value);
  const v = Number.isFinite(vRaw) ? vRaw : 0;
  // Use floored integer value for band matching so decimals map to their integer band
  const vLookup = Math.floor(Math.max(0, v));
  for (let i = 0; i < bands.length; i++) {
    const b = bands[i];
    if (vLookup >= b.min && vLookup <= b.max) {
      const skillAnchors = (anchors as any)[sk] || (anchors as any)[sk.replace(/\s+/g, '')] || {};
      const compAnchors = skillAnchors[canonicalComp] || skillAnchors[comp] || [];
      const foundAnchors = Array.isArray(compAnchors[i]) ? compAnchors[i] : (b as any).anchors || [];
      const mid = (b.max >= 50) ? 38 : Math.round((b.min + b.max) / 2);
      const process = Array.isArray((b as any).process) ? (b as any).process : [];
      const breakdown = Array.isArray((b as any).breakdown) ? (b as any).breakdown : [];
      const outcomes = Array.isArray((b as any).outcomes)
        ? (b as any).outcomes
        : ((b as any).description ? [String((b as any).description)] : []);
      const refuses = Array.isArray((b as any).refuses) ? (b as any).refuses : [];

      return {
        name: b.name,
        min: b.min,
        max: b.max,
        mid,
        anchors: foundAnchors,
        process,
        breakdown,
        outcomes,
        refuses,
        // keep legacy description for components that still expect it
        description: (b as any).description,
      };
    }
  }
  return { name: 'Unknown', description: '' };
}

export default referenceKey;

